export const content = {
  es: {
    navigation: ['Experiencia', 'Proyectos', 'Contacto'],
    theme: ['Tema claro', 'Tema oscuro'],
    viewGitHub: 'Ver GitHub',
    contact: 'Contactar',
    profile: 'Perfil',
    location: 'Ubicación',
    portfolio: 'Portafolio',
    publicRepositories: '20 repos públicos',
    portrait: 'Web · Apps · Servicios',
    professionalValue: '💼 Valor profesional',
    valueTitle: 'Lo que aporto desde el primer día.',
    trajectory: 'Trayectoria',
    experienceTitle: 'Experiencia que conecta tecnología y servicio.',
    technicalStack: '🧰 Stack técnico',
    stackTitle: 'Herramientas que uso para construir y desplegar.',
    professionalFocus: '🛡️ Enfoque profesional',
    softSkills: '🤝 Habilidades blandas',
    languages: '🌎 Idiomas',
    learning: '📚 En aprendizaje',
    education: '🎓 Formación',
    educationTitle: 'Títulos y formación académica.',
    certifications: '🏅 Certificaciones',
    certificationsTitle: 'Aprendizaje validado y continuo.',
    projects: '🚀 Proyectos destacados',
    projectsTitle: 'Productos reales, decisiones visibles.',
    allRepositories: 'Explorar todos los repositorios',
    code: 'Código',
    demo: 'Demo',
    downloads: '📄 Descargar CV',
    downloadsTitle: 'Tu CV, en el formato que necesites.',
    downloadsCopy: 'Disponible en formatos profesionales.',
    addFiles: 'Añade los archivos para activar la descarga',
    download: 'Descargar',
    contactEyebrow: '🤝 Conversemos',
    contactTitle: '¿Construimos algo que importe?',
    contactCopy: 'Estoy disponible para conversar sobre oportunidades Full Stack, productos digitales y colaboración tecnológica.',
    print: 'Imprimir / Guardar PDF',
    backToTop: 'Volver arriba',
    preview: 'Vista previa de'
  },
  en: {
    navigation: ['Experience', 'Projects', 'Contact'],
    theme: ['Light theme', 'Dark theme'],
    viewGitHub: 'View GitHub',
    contact: 'Contact',
    profile: 'Profile',
    location: 'Location',
    portfolio: 'Portfolio',
    publicRepositories: '20 public repositories',
    portrait: 'Web · Apps · Services',
    professionalValue: '💼 Professional value',
    valueTitle: 'What I bring from day one.',
    trajectory: 'Career',
    experienceTitle: 'Experience connecting technology and service.',
    technicalStack: '🧰 Technical stack',
    stackTitle: 'Tools I use to build and deploy.',
    professionalFocus: '🛡️ Professional focus',
    softSkills: '🤝 Soft skills',
    languages: '🌎 Languages',
    learning: '📚 Currently learning',
    education: '🎓 Education',
    educationTitle: 'Degrees and academic background.',
    certifications: '🏅 Certifications',
    certificationsTitle: 'Validated, continuous learning.',
    projects: '🚀 Featured projects',
    projectsTitle: 'Real products, visible decisions.',
    allRepositories: 'Explore all repositories',
    code: 'Code',
    demo: 'Demo',
    downloads: '📄 Download résumé',
    downloadsTitle: 'Your résumé, in the format you need.',
    downloadsCopy: 'Available in professional formats.',
    addFiles: 'Add the files to enable downloads',
    download: 'Download',
    contactEyebrow: '🤝 Let’s talk',
    contactTitle: 'Shall we build something that matters?',
    contactCopy: 'I am available to discuss Full Stack opportunities, digital products, and technology collaboration.',
    print: 'Print / Save PDF',
    backToTop: 'Back to top',
    preview: 'Preview of'
  }
}

export type ContentLabels = typeof content.es
