const asset = (name: string) => `${import.meta.env.BASE_URL}tool-icons/${name}.svg`

export const toolIcons: Record<string, string> = {
  JavaScript: asset('javascript'),
  TypeScript: asset('typescript'),
  Python: asset('python'),
  React: asset('react'),
  Django: asset('django'),
  'Node.js': asset('nodedotjs'),
  Express: asset('express'),
  Angular: asset('angular'),
  'Tailwind CSS': asset('tailwindcss'),
  Bootstrap: asset('bootstrap'),
  Bulma: asset('bulma'),
  PostgreSQL: asset('postgresql'),
  'SQL Server': asset('database'),
  MySQL: asset('mysql'),
  MongoDB: asset('mongodb'),
  MariaDB: asset('mariadb'),
  Oracle: asset('database'),
  AWS: asset('aws'),
  EC2: asset('aws-ec2'),
  S3: asset('aws-s3'),
  RDS: asset('aws-rds'),
  Cognito: asset('aws-cognito'),
  CloudFront: asset('aws-cloudfront'),
  'API Gateway': asset('aws-api-gateway'),
  Docker: asset('docker'),
  CloudFormation: asset('aws-cloudformation'),
  Vercel: asset('vercel'),
  Git: asset('git'),
  GitHub: asset('github'),
  GitLab: asset('gitlab'),
  Scrum: asset('engineering'),
  'APIs REST': asset('engineering'),
  JWT: asset('engineering'),
  Testing: asset('engineering'),
  '.NET': asset('dotnet'),
  Mattermost: asset('mattermost')
}
